version = 1

[[analyzers]]
name = "typescript"
enabled = true

  [analyzers.meta]
  environment = ["node"]
  plugins = ["react"]

  [analyzers.meta.rules]
  JS-0323 = "off" 
  ts/no-unsafe-any = "off"

[[transformers]]
name = "prettier"