// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  /**
   * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
   */
  interface GetMessageOptions {
    /**
     * See https://developer.chrome.com/docs/extensions/reference/i18n/#method-getMessage
     */
    escapeLt?: boolean
  }

  export interface WxtI18n extends I18n.Static {
    /**
     * The extension or app ID; you might use this string to construct URLs for resources inside the extension. Even unlocalized extensions can use this message.
     * Note: You can't use this message in a manifest file.
     *
     * "<browser.runtime.id>"
     */
    getMessage(
      messageName: "@@extension_id",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "<browser.i18n.getUiLocale()>"
     */
    getMessage(
      messageName: "@@ui_locale",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * The text direction for the current locale, either "ltr" for left-to-right languages such as English or "rtl" for right-to-left languages such as Japanese.
     *
     * "<ltr|rtl>"
     */
    getMessage(
      messageName: "@@bidi_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "rtl"; otherwise, it's "ltr".
     *
     * "<rtl|ltr>"
     */
    getMessage(
      messageName: "@@bidi_reversed_dir",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "left"; otherwise, it's "right".
     *
     * "<left|right>"
     */
    getMessage(
      messageName: "@@bidi_start_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * If the @@bidi_dir is "ltr", then this is "right"; otherwise, it's "left".
     *
     * "<right|left>"
     */
    getMessage(
      messageName: "@@bidi_end_edge",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Google Cloud Skills Boost - Helper"
     */
    getMessage(
      messageName: "extName",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Automatically modifies CloudSkillsBoost Labs with toggle options."
     */
    getMessage(
      messageName: "extDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Google Cloud Skills Boost - Helper Options"
     */
    getMessage(
      messageName: "optionsPageTitle",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Customize your experience with Google Cloud Skills Boost - Helper."
     */
    getMessage(
      messageName: "optionsPageDescription",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Feature"
     */
    getMessage(
      messageName: "labelFeature",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Action"
     */
    getMessage(
      messageName: "labelAction",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Show Leaderboard"
     */
    getMessage(
      messageName: "labelShowLeaderboard",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Hide Leaderboard"
     */
    getMessage(
      messageName: "labelHideLeaderboard",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "My Badges"
     */
    getMessage(
      messageName: "labelMyBadges",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Public Profile"
     */
    getMessage(
      messageName: "labelPublicProfile",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Arcade Points Calculator"
     */
    getMessage(
      messageName: "labelArcadePointsCalculator",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Save"
     */
    getMessage(
      messageName: "labelSave",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "No data available"
     */
    getMessage(
      messageName: "messageNoDataAvailable",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Recent Activity"
     */
    getMessage(
      messageName: "labelRecentActivity",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Badges & Achievements"
     */
    getMessage(
      messageName: "labelBadgesAchievements",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Update Points"
     */
    getMessage(
      messageName: "labelUpdatePoints",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Last Updated"
     */
    getMessage(
      messageName: "labelLastUpdated",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Page"
     */
    getMessage(
      messageName: "labelPage",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Load More"
     */
    getMessage(
      messageName: "labelLoadMore",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Current Level"
     */
    getMessage(
      messageName: "textCurrentLevel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Max level"
     */
    getMessage(
      messageName: "textMaxLevel",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Next level in"
     */
    getMessage(
      messageName: "textNextLevelInPoints",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "points"
     */
    getMessage(
      messageName: "textPoints",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    /**
     * "Please set up the settings"
     */
    getMessage(
      messageName: "textPleaseSetUpTheSettings",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
    getMessage(
      messageName: "@@extension_id" | "@@ui_locale" | "@@bidi_dir" | "@@bidi_reversed_dir" | "@@bidi_start_edge" | "@@bidi_end_edge" | "extName" | "extDescription" | "optionsPageTitle" | "optionsPageDescription" | "labelFeature" | "labelAction" | "labelShowLeaderboard" | "labelHideLeaderboard" | "labelMyBadges" | "labelPublicProfile" | "labelArcadePointsCalculator" | "labelSave" | "messageNoDataAvailable" | "labelRecentActivity" | "labelBadgesAchievements" | "labelUpdatePoints" | "labelLastUpdated" | "labelPage" | "labelLoadMore" | "textCurrentLevel" | "textMaxLevel" | "textNextLevelInPoints" | "textPoints" | "textPleaseSetUpTheSettings",
      substitutions?: string | string[],
      options?: GetMessageOptions,
    ): string;
  }
}
