name: Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn dev

      - name: Build Extension
        run: yarn build --zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/chrome-mv3-prod.zip
