name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build extension
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          yarn build --zip

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/chrome-mv3-prod.zip
