name: "Submit to Web Store"
on:
  push:
    branches:
      - dev
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    env:
      PLASMO_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the extension
        run: |
          yarn zip
          yarn zip:firefox --mv3
          yarn zip -b edge
          yarn zip -b opera

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "v.${{ github.ref_name }}"
          draft: true
          generate_release_notes: true
          body_path: INSTALL.md
          files: |
            .output/*-chrome.zip
            .output/*-firefox.zip
            .output/*-edge.zip
            .output/*-opera.zip
