name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          yarn install

      - name: Create Build Directory
        run: mkdir -p build

      - name: Build extension
        run: |
          yarn build --zip
          # for target in chrome-mv3 firefox-mv3 edge-mv3 brave-mv3 opera-mv3 safari-mv3; do
          #   yarn build --target=$target --zip
          # done

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/chrome-mv3-prod.zip
            # build/chrome-mv3-${{ env.VERSION }}.zip
            # build/edge-mv3-${{ env.VERSION }}.zip
            # build/brave-mv3-${{ env.VERSION }}.zip
            # build/opera-mv3-${{ env.VERSION }}.zip
            # build/safari-mv3-${{ env.VERSION }}.zip
