name: Release Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: node --max-old-space-size=4096 ./node_modules/.bin/npm run build --zip

      # - name: Generate Changelog
      #   run: echo "# Good things have arrived" > CHANGELOG.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/chrome-mv3-prod.zip
