name: "Submit to Web Store"
on:
  push:
    branches:
      - dev
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    env:
      PLASMO_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Create .npmrc file
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" > ~/.npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}" >> ~/.npmrc

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the extension
        run: |
          yarn build --target=chrome-mv3 --zip
          yarn build --target=firefox-mv3 --zip
          yarn build --target=edge-mv3 --zip
          yarn build --target=opera-mv3 --zip
          yarn build --target=safari-mv3 --zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "v.${{ github.ref_name }}"
          draft: true
          generate_release_notes: true
          files: |
            build/*.zip
