name: "Submit to Web Store"

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    env:
      PLASMO_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the extension
        run: |
          pnpm build --target=chrome-mv3 --zip
          pnpm build --target=firefox-mv3 --zip
          pnpm build --target=edge-mv3 --zip
          pnpm build --target=opera-mv3 --zip
          pnpm build --target=safari-mv3 --zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            build/*.zip
